from typing import Any, Dict, Set

class Vortex:
    def __init__(self): ...
    SECRETS: Dict[Any, Any] = ...
    endpoints: Set[Any] = ...

    def get_yml(self, yml_path): ...
    def get_env(self): ...
    def register_endpoint(self, func): ...